#!/usr/bin/env node

var path = require('path');
var spawn = require('child_process').spawn;

var serverDir = path.resolve(path.join(__dirname, 'server'));
var clientDir = path.resolve(path.join(__dirname, 'client'));

console.log('Starting backend...');
var serverProc = spawn('nodemon', ['bin/www'], { cwd: serverDir });

console.log('Starting Ember dev server...');
var emberProc = spawn('ember',
  ['serve'],
  { cwd: clientDir });

process.on('SIGINT', function() {
  console.log('exiting');
  serverProc.kill();
  emberProc.kill();

  process.exit();
});
